In [1]:
#!pip install openai

In [2]:
print('hello')

hello

In [168]:
import pandas as pd

df = pd.read_excel("diaries/Diari_annotati(25-07-25).xlsx",header=1)
df.head(2)

,note_descrittive,UO,N_diario,intervento_PV,esito valutato? (si/no),intervento_sicurezza,esito valutato? (si/no).1,intervento_terapia,esito valutato? (si/no).2,intervento_alimentazione e idratazione,...,intervento_riposo,esito valutato? (si/no).8,intervento_funzione_cardiocircolatoria,esito valutato? (si/no).9,intervento_comunicazione/educazione,esito valutato? (si/no).10,Altro/ Non classificato,esito valutato? (si/no).11,Presenza familiari,esito valutato? (si/no).12
0,RILEVATI PV NRS 0 TA 37.5TAMPONE COVID NEGATIV...,chirurgia,1.0,Rilevazione PV,no,Tampone Covid; Valutazione dolore,si,Somministrazione terapia,no,Rimozione SNG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rilevati PV ed eseguita assistenza. Nega algie...,chirurgia,1.0,Rilevazione PV,si,Valutazione dolore; monitoraggio drenaggio,si,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Erogata assistenza,no,NaN,NaN

In [170]:
# normalizza si, sí :
df["esito valutato? (si/no)"] = df["esito valutato? (si/no)"].replace({"sì": "si"})
# numero diario come intero
df["N_diario"] = pd.to_numeric(df["N_diario"], errors="coerce").astype("Int64")
df.head(5)

,note_descrittive,UO,N_diario,intervento_PV,esito valutato? (si/no),intervento_sicurezza,esito valutato? (si/no).1,intervento_terapia,esito valutato? (si/no).2,intervento_alimentazione e idratazione,...,intervento_riposo,esito valutato? (si/no).8,intervento_funzione_cardiocircolatoria,esito valutato? (si/no).9,intervento_comunicazione/educazione,esito valutato? (si/no).10,Altro/ Non classificato,esito valutato? (si/no).11,Presenza familiari,esito valutato? (si/no).12
0,RILEVATI PV NRS 0 TA 37.5TAMPONE COVID NEGATIV...,chirurgia,1,Rilevazione PV,no,Tampone Covid; Valutazione dolore,si,Somministrazione terapia,no,Rimozione SNG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rilevati PV ed eseguita assistenza. Nega algie...,chirurgia,1,Rilevazione PV,si,Valutazione dolore; monitoraggio drenaggio,si,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Erogata assistenza,no,NaN,NaN
2,Ha riposato. Apiretica,chirurgia,1,Rilevazione PV,si,NaN,NaN,NaN,NaN,NaN,...,Monitoraggio riposo,si,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RILEVATI PV NRS 0 DX 161 MG/DL SOMMINISTRATA T...,chirurgia,1,Rilevazione PV,si,Valutazione dolore; Monitoraggio drenaggi; ril...,si,Somministrazione terapia,no,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ESEGUITA TAC,chirurgia,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [180]:
df['intervento_sicurezza'].iloc[0]

'Tampone Covid; Valutazione dolore'

In [174]:
lista_diari = df["note_descrittive"].tolist()

lista_diari[0:4]

['RILEVATI PV NRS 0 TA 37.5TAMPONE COVID NEGATIVO\xa0SOMMINISTRATA TERAPIA\xa0E. TA ASSISTENZA\xa0DOMANI MATTINA ESEGUE TACPZ SI RIMUOVE SNG----> 400 CC',
 'Rilevati PV ed eseguita assistenza. Nega algie. TA 37.5 somm.to tp. H 21 DRENAGGIO ADDOME DX 100 ML SIERO/EMATICODRENAGGIO ADDOME SX 200 ML SIERO/EMATICO',
 'Ha riposato. Apiretica',
 'RILEVATI PV NRS 0 DX 161 MG/DL\xa0SOMMINISTRATA TERAPIA\xa0E. TA ASSISTENZA\xa0IN ATTESA DI TAC\xa0']

# GPT

In [11]:
import json
import os
from dotenv import load_dotenv

from openai import OpenAI

In [176]:
OPENAI_MODEL = "gpt-5-mini" #gpt-5-mini, gpt-4o-mini 
SYSTEM_PROMPT = """Sei un esperto di minfermieristica ."""
USER_INSTRUCTIONS = """Assegna una categoria al  prompt che è un diario infermieristico basata su queste categorie: 
assessment
valutazione dolore
monitoraggio drenaggio
posizionato/riposizionato cvp
esami ematici
medicazione cvc
assessment, valutazione dolore
emocolture
rilevata glicemia
gestione cvc
tampone antigenico
tampone covid
catetere arterioso radiale (gest/med)
rimosso cvc
tampone rapido
emogasanalisi (ega)
gestione elastomero
medicazione compressiva
medicazione lesione sovraombelicale
posizionamento monitor
posizionato mad
presenza della figlia in camera, senza permesso e senza requisiti di sicurezza
rimosso cvc radiale
rimosso cvp
sostituito cvp
tampone
tampone faringeo
urinocoltura
valutazione del dolore: monitoraggio cvc.

 Puoi dare 0, 1 o 2 classificazioni per il diario nel prompt.
 L'output deve essere:
' 1- Categoria, 2-categoria'
oppure :
'no classification'  """

In [152]:
# Chiave API
load_dotenv()
api_key = os.getenv("OPENAI_API_KEY_CHAT")
client = OpenAI(api_key=api_key)

In [ ]:
testo_diario="""RILEVATI PV NRS 0 TA 37.5TAMPONE COVID NEGATIVO SOMMINISTRATA TERAPIA E. TA ASSISTENZA DOMANI MATTINA ESEGUE TACPZ SI RIMUOVE SNG----> 400 CC"""

In [177]:
resp = client.responses.create(
	model=OPENAI_MODEL,
	instructions=SYSTEM_PROMPT,
	input=USER_INSTRUCTIONS + testo_diario + "\n---"
)
print(resp.output_text) 
# data = json.loads(resp.output_text)
# print(json.dumps(data, indent=4, ensure_ascii=False))

' 1- valutazione dolore, 2- tampone covid'

In [183]:
for i,text in enumerate(lista_diari[:15]):
    resp = client.responses.create(
	model=OPENAI_MODEL,
	instructions=SYSTEM_PROMPT,
	input=USER_INSTRUCTIONS + text + "\n---"
    )
    
    print('output:\t ',resp.output_text)
    print('verità:\t ',df['intervento_sicurezza'].iloc[i], '\n')

# data = json.loads(resp.output_text)
# print(json.dumps(data, indent=4, ensure_ascii=False))

output:	  ' 1- valutazione dolore, 2-tampone covid'
verità:	  Tampone Covid; Valutazione dolore

output:	  ' 1- monitoraggio drenaggio, 2- valutazione dolore'
verità:	  Valutazione dolore; monitoraggio drenaggio

output:	  ' 1- assessment, 2-'
verità:	  nan

output:	  ' 1- valutazione dolore, 2-rilevata glicemia'
verità:	  Valutazione dolore; Monitoraggio drenaggi; rilevata glicemia

output:	  no classification
verità:	  nan

output:	  ' 1- assessment, 2- valutazione dolore'
verità:	  Assessment; Valutazione dolore

output:	   1- emocolture, 2- gestione cvc
verità:	  Emocolture da CVC e CVP

output:	  1- assessment, 2-
verità:	  nan

output:	  ' 1- monitoraggio drenaggio, 2- '
verità:	  Monitoraggio drenaggi

output:	  1- assessment
verità:	  nan

output:	   1- emocolture, 2-posizionato/riposizionato cvp
verità:	  Valutazione dolore; Emocolture da PICC e CVP; posizionato CVP; EGA

output:	  ' 1- assessment, 2-rilevata glicemia'
verità:	  Assessment; Valutazione dolore; Rilevata glicemia

output:	  1- assessment, 2-
verità:	  nan

output:	  1- assessment, 2-
verità:	  nan

output:	  ' 1- emocolture, 2-valutazione dolore'
verità:	  Emocolture; Valutazione dolore

In [186]:
lista_diari[-10:]

['Paziente in scadenti condizioni cliniche: soporosa ma risvegliabile allo stimolo verbale, collaborante nei limiti. Apiretica. Mantiene O2 terapia con canule nasali a 1lt/min. Diuresi attiva in CV con urine normocromiche. Somministrata terapia secondo schema. Idratata per OS. In corso dobutamina e lasix in pompa. Paziente mantenuta in posiziona semi-seduta. Rilevati PV alle ore 21: PA 117/60 mmHg, FC 100bpm, SpO2 90% in O2 terapia. Durante il turno presenta degli episodi di agitazione e di disorientamento, si rilevano PV: SpO2 risulta intorno a 82%-84% con O2 terapia a 1lt/min, si avvisa medico di guardia che predispone per CN 2lt/min. Assistita al bisogno.\xa0 AASS esematosi, posizionati in scarico.\xa0Al momento PV: PA 120/60mmHg, FC 98bpm, SpO2 92% con O2 terapia 2lt/min.',
 'PV ore 6: PA 130/60mmHg, FC 95bpm, SpO2 92% con O2 terapia 2lt/min',
 'pz a tratti soporosa/ vigile. Somm.ta tp spm, Urine in cv normocromiche.',
 'Rilevati i PV ( PA 135/62 mmHg, FC 94 bpm, SpO2 92 con CN a 2 lt/min). Diuresi attiva in CV ( attualmente circa 230 ml di urine normocromiche). Pz lamenta dolore addominale. Somministrata la tp AB ( 0.5 fl di Paracetamolo EV), con beneficio. In accordo con i Parenti NON si contatta il MdG. Presenti Parenti.',
 'Pz soporosa. Anurica. Non somministrata la tp per OS.',
 'Pz in scadenti condizioni cliniche generali, tendente al sopore ma risvegliabile allo stimolo verbale, collaborante. Somministrata tp secondo schema ed in corso tp ev come da indicazione medica. Mantiene O2 tp come da indicazione medica. Apparentemente non sofferente.\xa0AASS in scarico perchè edematosi.\xa0Ore 21:00 PA 128/88, SpO2 91% con O2 tp, FC 73 btt/min ed apiretica. Eseguita assistenza ed assistita al bisogno.\xa0Ore 00:30 circa PA 130/80, SpO2 90% con O2 tp, FC 82 btt/min.\xa0Al momento a tratti riposa e a tratti è vigile e confusa.',
 'PA 140/85, SpO2 90% con O2 tp, FC 86 btt/min. Pz stabile nelle sue condizioni. Ha riposato a tratti.',
 'Pz in scadenti condizioni.\xa0Somministrata la tp secondo prescr medica ( la tp tritata per OS+ tp EV). Si alimenta a colazione per OS con aiuto . Presenti Parenti.',
 'pz in scadentissime condizioni generali.\xa0Assistita al bisogno. Prosegue tp in pompa a infusione . O2 tp in sede\xa0In apparenza non sofferente. Presenti parenti con lei in stanza\xa0',
 'pz soporosa, assistita al bisogno. Non appare sofferente. Mantiene cn, lasix ic. Al momento riposa.']

In [188]:
k=20
lista_diari[k:k+10]

['pz tranquilla in terapia\xa0 apiretica nella notte solita assistenza',
 'sng 700 cc.',
 'Rilevati parametri vitali, nega algie e/o nausea. Somministrata terapia prescritta ed eseguita assistenza.\xa0SNG chiuso. Interrotta O2 th con occhialini. Riposizionato cvp',
 'Pz stazionaria, pv nella norma, apiretica, nega algie. Somm tp come da prescrizione',
 'Paziente stazionaria, vigile e responsiva , misurati parametri vitali. Paziente nega algie e nausea. Eseguita assistenza. Diuresi attiva.',
 'ha riposato, posizionato accesso venoso',
 'Paziente riferisce bruciore di stomaco, anticipato terapia EV Pantorc 40 mg in soluzione fisiologica da 100 ml delle h 8.00',
 'Paziente riferisce bruciore di stomaco, anticipato terapia EV Pantorc 40 mg in soluzione fisiologica da 100 ml delle h 8.00',
 'rilevati parametri eseguita terapia e assistenza',
 'Pz stazionaria, pv nella norma, nega algie. Somm tp come da prescrizione']

In [202]:
i=0
k=20

for i in range(k, k+10):
    print(i, lista_diari[i])

20 pz tranquilla in terapia  apiretica nella notte solita assistenza
21 sng 700 cc.
22 Rilevati parametri vitali, nega algie e/o nausea. Somministrata terapia prescritta ed eseguita assistenza. SNG chiuso. Interrotta O2 th con occhialini. Riposizionato cvp
23 Pz stazionaria, pv nella norma, apiretica, nega algie. Somm tp come da prescrizione
24 Paziente stazionaria, vigile e responsiva , misurati parametri vitali. Paziente nega algie e nausea. Eseguita assistenza. Diuresi attiva.
25 ha riposato, posizionato accesso venoso
26 Paziente riferisce bruciore di stomaco, anticipato terapia EV Pantorc 40 mg in soluzione fisiologica da 100 ml delle h 8.00
27 Paziente riferisce bruciore di stomaco, anticipato terapia EV Pantorc 40 mg in soluzione fisiologica da 100 ml delle h 8.00
28 rilevati parametri eseguita terapia e assistenza
29 Pz stazionaria, pv nella norma, nega algie. Somm tp come da prescrizione

In [ ]:
k= 20

for i in range(k, k+10):
    resp = client.responses.create(
	model=OPENAI_MODEL,
	instructions=SYSTEM_PROMPT,
	input=USER_INSTRUCTIONS + lista_diari[i] + "\n---"
    )
    
    print(i)
    print(lista_diari[i])
    print('output:\t ',resp.output_text)
    print('verità:\t ',df['intervento_sicurezza'].iloc[i], '\n')

20
pz tranquilla in terapia  apiretica nella notte solita assistenza
output:	  ' 1- assessment, 2-'
verità:	  Assessment

# DATA CLEANING

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 29 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   note_descrittive                        412 non-null    object
 1   UO                                      412 non-null    object
 2   N_diario                                411 non-null    Int64
 3   intervento_PV                           213 non-null    object
 4   esito valutato? (si/no)                 212 non-null    object
 5   intervento_sicurezza                    178 non-null    object
 6   esito valutato? (si/no).1               165 non-null    object
 7   intervento_terapia                      178 non-null    object
 8   esito valutato? (si/no).2               177 non-null    object
 9   intervento_alimentazione e idratazione  37 non-null     object
 10  esito valutato? (si/no).3               35 non-null     object
 11  intervento_respirare                    30 non-null     object
 12  esito valutato? (si/no).4               30 non-null     object
 13  intervento_eliminazione                 60 non-null     object
 14  esito valutato? (si/no).5               58 non-null     object
 15  intervento_igiene                       2 non-null      object
 16  esito valutato? (si/no).6               2 non-null      object
 17  intervento_movimento                    13 non-null     object
 18  esito valutato? (si/no).7               13 non-null     object
 19  intervento_riposo                       63 non-null     object
 20  esito valutato? (si/no).8               63 non-null     object
 21  intervento_funzione_cardiocircolatoria  0 non-null      float64
 22  esito valutato? (si/no).9               0 non-null      float64
 23  intervento_comunicazione/educazione     3 non-null      object
 24  esito valutato? (si/no).10              3 non-null      object
 25  Altro/ Non classificato                 127 non-null    object
 26  esito valutato? (si/no).11              125 non-null    object
 27  Presenza familiari                      5 non-null      object
 28  esito valutato? (si/no).12              5 non-null      object
dtypes: Int64(1), float64(2), object(26)
memory usage: 93.9+ KB

## Intervento_SIcurezza categorie

In [172]:
df["intervento_sicurezza"].value_counts().to_csv("intervento_sicurezza_counts_0.csv")

In [173]:
df["intervento_sicurezza"].str.split(";")

0                   [Tampone Covid,  Valutazione dolore]
1          [Valutazione dolore,  monitoraggio drenaggio]
2                                                    NaN
3      [Valutazione dolore,  Monitoraggio drenaggi,  ...
4                                                    NaN
                             ...
407                                                  NaN
408                                                  NaN
409                                                  NaN
410                                                  NaN
411                                                  NaN
Name: intervento_sicurezza, Length: 412, dtype: object

In [135]:

df["intervento_sicurezza_list"] = df["intervento_sicurezza"].str.split(";")
df_exploded = df.explode("intervento_sicurezza_list")
df_exploded.head()

,note_descrittive,UO,N_diario,intervento_PV,esito valutato? (si/no),intervento_sicurezza,esito valutato? (si/no).1,intervento_terapia,esito valutato? (si/no).2,intervento_alimentazione e idratazione,...,esito valutato? (si/no).8,intervento_funzione_cardiocircolatoria,esito valutato? (si/no).9,intervento_comunicazione/educazione,esito valutato? (si/no).10,Altro/ Non classificato,esito valutato? (si/no).11,Presenza familiari,esito valutato? (si/no).12,intervento_sicurezza_list
0,RILEVATI PV NRS 0 TA 37.5TAMPONE COVID NEGATIV...,chirurgia,1,Rilevazione PV,no,Tampone Covid; Valutazione dolore,si,Somministrazione terapia,no,Rimozione SNG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tampone Covid
0,RILEVATI PV NRS 0 TA 37.5TAMPONE COVID NEGATIV...,chirurgia,1,Rilevazione PV,no,Tampone Covid; Valutazione dolore,si,Somministrazione terapia,no,Rimozione SNG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valutazione dolore
1,Rilevati PV ed eseguita assistenza. Nega algie...,chirurgia,1,Rilevazione PV,si,Valutazione dolore; monitoraggio drenaggio,si,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Erogata assistenza,no,NaN,NaN,Valutazione dolore
1,Rilevati PV ed eseguita assistenza. Nega algie...,chirurgia,1,Rilevazione PV,si,Valutazione dolore; monitoraggio drenaggio,si,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Erogata assistenza,no,NaN,NaN,monitoraggio drenaggio
2,Ha riposato. Apiretica,chirurgia,1,Rilevazione PV,si,NaN,NaN,NaN,NaN,NaN,...,si,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
df_exploded["intervento_sicurezza_list"].value_counts().to_csv("intervento_sicurezza_counts_1.csv")

In [138]:
cols = df_exploded.columns.tolist()

col = "intervento_sicurezza_list"

# togli la colonna dalla lista e reinseriscila in posizione 2 (che è la terza, contando da 0)
cols.remove(col)
cols.insert(7, col)

# riordina il DataFrame
df_exploded = df_exploded[cols]
df_exploded.head(5)

,note_descrittive,UO,N_diario,intervento_PV,esito valutato? (si/no),intervento_sicurezza,esito valutato? (si/no).1,intervento_sicurezza_list,intervento_terapia,esito valutato? (si/no).2,...,intervento_riposo,esito valutato? (si/no).8,intervento_funzione_cardiocircolatoria,esito valutato? (si/no).9,intervento_comunicazione/educazione,esito valutato? (si/no).10,Altro/ Non classificato,esito valutato? (si/no).11,Presenza familiari,esito valutato? (si/no).12
0,RILEVATI PV NRS 0 TA 37.5TAMPONE COVID NEGATIV...,chirurgia,1,Rilevazione PV,no,Tampone Covid; Valutazione dolore,si,Tampone Covid,Somministrazione terapia,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,RILEVATI PV NRS 0 TA 37.5TAMPONE COVID NEGATIV...,chirurgia,1,Rilevazione PV,no,Tampone Covid; Valutazione dolore,si,Valutazione dolore,Somministrazione terapia,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rilevati PV ed eseguita assistenza. Nega algie...,chirurgia,1,Rilevazione PV,si,Valutazione dolore; monitoraggio drenaggio,si,Valutazione dolore,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Erogata assistenza,no,NaN,NaN
1,Rilevati PV ed eseguita assistenza. Nega algie...,chirurgia,1,Rilevazione PV,si,Valutazione dolore; monitoraggio drenaggio,si,monitoraggio drenaggio,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Erogata assistenza,no,NaN,NaN
2,Ha riposato. Apiretica,chirurgia,1,Rilevazione PV,si,NaN,NaN,NaN,NaN,NaN,...,Monitoraggio riposo,si,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [128]:
df_exploded["intervento_sicurezza_list"].value_counts()

intervento_sicurezza_list
assessment                                                                        109
valutazione dolore                                                                 88
monitoraggio drenaggio                                                             11
posizionato/riposizionato cvp                                                       7
esami ematici                                                                       6
medicazione cvc                                                                     6
assessment, valutazione dolore                                                      5
rilevata glicemia                                                                   5
emocolture                                                                          5
tampone covid                                                                       3
gestione cvc                                                                        3
tampone antigenico                                                                  3
catetere arterioso radiale (gest/med)                                               2
rimosso cvc                                                                         2
tampone rapido                                                                      2
presenza della figlia in camera, senza permesso e senza requisiti di sicurezza      1
posizionamento monitor                                                              1
medicazione lesione sovraombelicale                                                 1
medicazione compressiva                                                             1
posizionato mad                                                                     1
rimosso cvc radiale                                                                 1
valutazione del dolore: monitoraggio cvc                                            1
gestione elastomero                                                                 1
sostituito cvp                                                                      1
tampone                                                                             1
emogasanalisi (ega)                                                                 1
urinocoltura                                                                        1
rimosso cvp                                                                         1
tampone faringeo                                                                    1
Name: count, dtype: int64

In [139]:
# pulire righe con spazi e maiuscole minuscole :"intervento_sicurezza_list"

df_exploded["intervento_sicurezza_list"] = (
    df_exploded["intervento_sicurezza_list"]
    .str.strip()        # toglie spazi in eccesso
    .str.lower()        # tutto minuscolo
)

In [140]:
df_exploded["intervento_sicurezza_list"].value_counts().to_csv("intervento_sicurezza_counts_2.csv")

In [141]:
# mappings di cose uguali
col = "intervento_sicurezza_list"

mapping_conserv = {
    "asssessment": "assessment",
    "valutazione del dolore": "valutazione dolore",
    "monitoraggio drenaggi": "monitoraggio drenaggio",
    "rimosso il cvc": "rimosso cvc",
    "assesment, valutazione dolore" : "assessment, valutazione dolore"
}
df_exploded[col] = df_exploded[col].replace(mapping_conserv)

In [107]:
df_exploded["intervento_sicurezza_list"].value_counts()

intervento_sicurezza_list
assessment                                                                        109
valutazione dolore                                                                 88
monitoraggio drenaggio                                                             11
posizionato/riposizionato cvp                                                       7
medicazione cvc                                                                     6
esami ematici                                                                       6
assessment, valutazione dolore                                                      5
rilevata glicemia                                                                   5
emocolture                                                                          5
tampone covid                                                                       3
tampone antigenico                                                                  3
gestione cvc                                                                        2
tampone rapido                                                                      2
rimosso cvc                                                                         2
catetere arterioso radiale (gest/med)                                               2
presenza della figlia in camera, senza permesso e senza requisiti di sicurezza      1
posizionamento monitor                                                              1
medicazione lesione sovraombelicale                                                 1
medicazione compressiva                                                             1
posizionato mad                                                                     1
rimosso cvc radiale                                                                 1
valutazione del dolore: monitoraggio cvc                                            1
gestione elastomero                                                                 1
sostituito cvp                                                                      1
tampone                                                                             1
emogasanalisi (ega)                                                                 1
urinocoltura                                                                        1
cvc                                                                                 1
rimosso cvp                                                                         1
tampone faringeo                                                                    1
Name: count, dtype: int64

In [142]:
df_exploded["intervento_sicurezza_list"].value_counts().to_csv("intervento_sicurezza_counts_3.csv")

In [143]:
# etichette piu comprensive e pulite, mapping finale:

mapping = {
    # dolore / assessment
    "valutazione del dolore": "valutazione dolore",
    "valutaizone del dolore": "valutazione dolore",
    "assesment": "assessment",
    "asssessment": "assessment",
    # drenaggi
    "monitoraggio drenaggi": "monitoraggio drenaggio",
    # esami ematici
    "eseguiti esami ematici": "esami ematici",
    "esegue esami ematici": "esami ematici",
    # glicemia
    "hgt": "rilevata glicemia",
    # cvp/cvc
    "riposizionato cvp": "posizionato/riposizionato cvp",
    "posizionato cvp": "posizionato/riposizionato cvp",
    "medicazione compressiva cvc": "medicazione cvc",
    "medicazione emostatica cvc": "medicazione cvc",
    "medicazione sede cvc": "medicazione cvc",
    "cvc": "gestione cvc",
    # catetere arterioso radiale
    "gestione catetere arterioso radiale": "catetere arterioso radiale (gest/med)",
    "medicazione catetere arterioso radiale": "catetere arterioso radiale (gest/med)",
    # emocolture
    "emocolture da cvc e cvp": "emocolture",
    "emocolture da picc e cvp": "emocolture",
    "eseguite emocolture": "emocolture",
    # tamponi (macro)
    "test antigenico per covid": "tampone covid",
    "eseguito tampone": "tampone",
    "eseguito tampone rapido": "tampone rapido",

    # altro
    "ega": "emogasanalisi (EGA)",
}

# applica
col = "intervento_sicurezza_list"
df_exploded[col] = df_exploded[col].str.strip().str.lower().replace(r"\s+", " ", regex=True)
df_exploded[col] = df_exploded[col].replace(mapping)

# NB: per le voci combinate va prima fatto lo split:
# "assessment, valutazione dolore" -> split su virgola o ":" prima di replace

In [144]:
df_exploded["intervento_sicurezza_list"].value_counts().to_csv("intervento_sicurezza_counts_4.csv")

In [109]:
df_exploded["intervento_sicurezza_list"].value_counts()

intervento_sicurezza_list
assessment                                                                        109
valutazione dolore                                                                 88
monitoraggio drenaggio                                                             11
posizionato/riposizionato cvp                                                       7
esami ematici                                                                       6
medicazione cvc                                                                     6
assessment, valutazione dolore                                                      5
rilevata glicemia                                                                   5
emocolture                                                                          5
tampone covid                                                                       3
gestione cvc                                                                        3
tampone antigenico                                                                  3
catetere arterioso radiale (gest/med)                                               2
rimosso cvc                                                                         2
tampone rapido                                                                      2
presenza della figlia in camera, senza permesso e senza requisiti di sicurezza      1
posizionamento monitor                                                              1
medicazione lesione sovraombelicale                                                 1
medicazione compressiva                                                             1
posizionato mad                                                                     1
rimosso cvc radiale                                                                 1
valutazione del dolore: monitoraggio cvc                                            1
gestione elastomero                                                                 1
sostituito cvp                                                                      1
tampone                                                                             1
emogasanalisi (ega)                                                                 1
urinocoltura                                                                        1
rimosso cvp                                                                         1
tampone faringeo                                                                    1
Name: count, dtype: int64

In [115]:
vc = df_exploded["intervento_sicurezza_list"].value_counts().reset_index()
vc.columns = ["intervento_sicurezza_list", "count"]

# ordina prima per count (discendente), poi per nome (ascendente)
vc = vc.sort_values(by=["count", "intervento_sicurezza_list"],
                    ascending=[False, True])

print(vc)

                            intervento_sicurezza_list  count
0                                          assessment    109
1                                  valutazione dolore     88
2                              monitoraggio drenaggio     11
3                       posizionato/riposizionato cvp      7
4                                       esami ematici      6
5                                     medicazione cvc      6
6                      assessment, valutazione dolore      5
8                                          emocolture      5
7                                   rilevata glicemia      5
10                                       gestione cvc      3
11                                 tampone antigenico      3
9                                       tampone covid      3
12              catetere arterioso radiale (gest/med)      2
13                                        rimosso cvc      2
14                                     tampone rapido      2
25                                emogasanalisi (ega)      1
22                                gestione elastomero      1
18                            medicazione compressiva      1
17                medicazione lesione sovraombelicale      1
16                             posizionamento monitor      1
19                                    posizionato mad      1
15  presenza della figlia in camera, senza permess...      1
20                                rimosso cvc radiale      1
27                                        rimosso cvp      1
23                                     sostituito cvp      1
24                                            tampone      1
28                                   tampone faringeo      1
26                                       urinocoltura      1
21           valutazione del dolore: monitoraggio cvc      1

In [145]:
vc.to_csv("intervento_sicurezza_counts_4.csv", 
          index=False)

In [ ]:
v

In [110]:
print(df.shape)
display(df.groupby("UO").count())
df["UO"].value_counts()

(412, 30)

,note_descrittive,N_diario,intervento_PV,esito valutato? (si/no),intervento_sicurezza,esito valutato? (si/no).1,intervento_terapia,esito valutato? (si/no).2,intervento_alimentazione e idratazione,esito valutato? (si/no).3,...,esito valutato? (si/no).8,intervento_funzione_cardiocircolatoria,esito valutato? (si/no).9,intervento_comunicazione/educazione,esito valutato? (si/no).10,Altro/ Non classificato,esito valutato? (si/no).11,Presenza familiari,esito valutato? (si/no).12,intervento_sicurezza_list
UO,,,,,,,,,,,,,,,,,,,,,
chirurgia,263,262,191,190,139,130,150,149,30,28,...,58,0,0,3,3,110,108,0,0,139
medicina,149,149,22,22,39,35,28,28,7,7,...,5,0,0,0,0,17,17,5,5,39

UO
chirurgia    263
medicina     149
Name: count, dtype: int64